# include /etc/bashrc if it exists
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

echo -e "\e[137m"
fortune
echo -e "\e[0m"

eval "$(zoxide init bash)"
alias cd="z"

alias ls="eza"

alias pull='sudo git pull origin main'

alias rb='sudo nixos-rebuild switch --flake .#'

eval "$(starship init bash)"

