#!/usr/bin/env bash

set -e
mkdir -p /tmp/log
echo "Put system to sleep at: $(date)" >> /tmp/log/sleep.log 2>&1

for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
echo powersave > "$cpu"
done

systemctl stop minecraft-server-modded.service

${pkgs.curl}/bin/curl -d "$(hostname) Put server to sleep mode at: $(date) succesfully " ntfy.sh/server_cron_jobs